# Generated by Django 4.1rc1 on 2022-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_birthdate_user_language_alter_user_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("EN", "English"), ("KR", "Korean")],
                default="KR",
                max_length=2,
            ),
        ),
    ]
