# Generated by Django 4.1rc1 on 2022-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("KRW", "KRW")], default="KRW", max_length=3
            ),
        ),
    ]
