# Generated by Django 4.1rc1 on 2022-07-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_superhost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="avatars"),
        ),
    ]
