# Generated by Django 4.1rc1 on 2022-07-26 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0008_alter_amenity_options_alter_facility_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("review", models.TextField()),
                ("accuracy", models.DecimalField(decimal_places=1, max_digits=2)),
                ("communication", models.DecimalField(decimal_places=1, max_digits=2)),
                ("cleanliness", models.DecimalField(decimal_places=1, max_digits=2)),
                ("localtion", models.DecimalField(decimal_places=1, max_digits=2)),
                ("check_in", models.DecimalField(decimal_places=1, max_digits=2)),
                ("value", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
